name: Build and Upload Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write
  id-token: write

# env:
#   CLOUDSMITH_NAMESPACE: ${{ vars.CLOUDSMITH_NAMESPACE }}
#   CLOUDSMITH_STAGING_REPO: 'staging'
#   CLOUDSMITH_SERVICE_SLUG: ${{ vars.CLOUDSMITH_SERVICE_SLUG }}

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: python-package
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: python -m build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/
          if-no-files-found: error
          retention-days: 7

      # - name: Authenticate with Cloudsmith (OIDC)
      #   uses: cloudsmith-io/cloudsmith-cli-action@v1.0.1
      #   with:
      #     oidc-namespace: ${{ env.CLOUDSMITH_NAMESPACE }}
      #     oidc-service-slug: ${{ env.CLOUDSMITH_SERVICE_SLUG }}

      # - name: Upload package to Cloudsmith staging repo
      #   run: |
      #     echo "Uploading built package(s) to Cloudsmith staging..."
      #     cloudsmith push python \
      #       ${{ env.CLOUDSMITH_NAMESPACE }}/${{ env.CLOUDSMITH_STAGING_REPO }} \
      #       dist/*.tar.gz
